defmodule MastheadWeb.CacheBodyReader do
  @moduledoc """
  Body reader for `Plug.Parsers` that keeps the exact bytes of a payment
  webhook, which is what its signature is computed over.

  Only the webhook path is buffered. Caching every request would hold whole
  theme zips and image uploads in memory on their way through the parser.
  """
  @webhook_path "/webhooks/payments"

  def read_body(%Plug.Conn{request_path: @webhook_path} = conn, opts) do
    {:ok, body, conn} = Plug.Conn.read_body(conn, opts)
    {:ok, body, Plug.Conn.assign(conn, :raw_body, body)}
  end

  def read_body(conn, opts), do: Plug.Conn.read_body(conn, opts)
end

defmodule MastheadWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :masthead

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_masthead_key",
    signing_salt: "eAAftYv+",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :masthead,
    gzip: not code_reloading?,
    only: MastheadWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  plug Plug.Static,
    at: "/uploads",
    from: {Masthead.Storage, :root_path, []},
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :masthead
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {MastheadWeb.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MastheadWeb.SiteDispatcher
  plug MastheadWeb.Router
end
